kind: Service
apiVersion: v1
metadata:
  name: backend-deployment
  labels:
    name: backend-deployment
spec:
  ports:
    # - nodePort: 30163 
    - port: 8500      
      targetPort: 8500  
      protocol: TCP
  selector:           
    app: backend-deployment
  # type: NodePort       

---
apiVersion: apps/v1 
kind: Deployment    
metadata:              
  name: backend-deployment
spec:                
  selector:         
    matchLabels:
      app: backend-deployment
  replicas: 1        
  template:
    metadata:
      labels:        
        app: backend-deployment
    spec:
      containers:
        - name: backend-deployment
          image: gradeus-backend:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8500                
          env:   # Setting Enviornmental Variables
          - name: MYSQL_HOST   # Setting Database host address from configMap
            valueFrom: 
              configMapKeyRef:
                name: db-conf  # name of configMap
                key: host
          - name: MYSQL_DATABASE  # Setting Database name from configMap
            valueFrom:
              configMapKeyRef:
                name: db-conf 
                key: name
          - name: MYSQL_USER  # Setting Database username from Secret
            valueFrom:
              secretKeyRef:
                name: db-credentials # Secret Name
                key: username
          - name: MYSQL_PASSWORD # Setting Database password from Secret
            valueFrom:
              secretKeyRef:
                name: db-credentials
                key: password     
        