---
  - name: "Deploying on the kubernetes cluster"
    hosts: localhost
    connection: local 
    
    tasks:
    # - name: Azure cli login
    #   ansible.builtin.shell:
    #     cmd: "az login -u {{ lookup('env', 'MJP_AZURE_USER') }} -p {{ lookup('env', 'MJP_AZURE_PASSWORD') }}"

    - name: Deploying logstash and filebeats inside the kubernetes cluster
      ansible.builtin.shell: |
        helm upgrade --install filebeat kubeDeploy/filebeat
        helm upgrade --install logstash kubeDeploy/logstash
      environment:
        KUBECONFIG: "/Users/lovejeetsingh/confKube"

    - name: Adding secrets and config maps to kubernetes cluster
      ansible.builtin.shell: |
        kubectl apply -f kubeDeploy/mysql-root-credentials.yml
        kubectl apply -f kubeDeploy/mysql-credentials.yml
        kubectl apply -f kubeDeploy/mysql-configmap.yml
      environment:
        KUBECONFIG: "/Users/lovejeetsingh/confKube"

    - name: Deleting older application deployment
      ansible.builtin.shell: |
        kubectl delete -f kubeDeploy/mysql-deployment.yml --ignore-not-found=true
        kubectl delete -f kubeDeploy/backend-deployment.yml --ignore-not-found=true
        kubectl delete -f kubeDeploy/frontend-deployment.yml --ignore-not-found=true
      environment:
        KUBECONFIG: "/Users/lovejeetsingh/confKube"

    - name: Deploying application to kubernetes cluster
      ansible.builtin.shell: |
        kubectl apply -f kubeDeploy/mysql-service.yml
        kubectl apply -f kubeDeploy/mysql-pvc.yml
        kubectl apply -f kubeDeploy/mysql-deployment.yml
        kubectl apply -f kubeDeploy/backend-service.yml
        kubectl apply -f kubeDeploy/backend-deployment.yml
        kubectl apply -f kubeDeploy/frontend-service.yml
        kubectl apply -f kubeDeploy/frontend-deployment.yml
      environment:
        KUBECONFIG: "/Users/lovejeetsingh/confKube"
