server:
  port: 8500

spring:
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:${MYSQL_URL:3306}/${MYSQL_DATABASE:gradeus}
    username: ${MYSQL_USER:gradeus}
    password: ${MYSQL_PASSWORD:gradeus}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
