server:
  port: 8500

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/gradeus
    username: gradeus
    password: gradeus
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
